### PR TITLE
Update projects.yml

### PR DESCRIPTION
**Pull request by mcraken**
I added a project of mine to the list. Thanks in advance.

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks @mcraken!

It'd be great if there were a list of issues on the repository of features/bugs/suggestions that could be contributed to the project by others. Would that be possible to do, so visitors don't land on the page and find themselves uncertain of what they can help out with?

**Comment by mcraken** [comment]
Thanks for you comment @shiftkey 

Sure I would do what you have asked, but I'm already building a readme for the repository. I'm trying to explain the project and I'm providing some sort of a to-do list at the end.

Would you kindly check it out and suggest what to do or how to optimize it?

**Comment by shiftkey** [comment]
@mcraken we added some notes to the end of the home page:

---

### What sort of tasks are a good fit?
- Tasks should take no longer than a few nights' worth of work
- Tasks should stand alone - avoid core functionality on which other tasks depend
- Tasks should be well described with pointers to help the implementer

**Comment by mcraken** [comment]
@shiftkey Ok, working on it.

**Comment by shiftkey** [comment]
We've made some changes to how projects are added in #160 - once you've got these tasks fleshed out I'd love to add the project to the list!

**Pull request closed without merging**
