### PR TITLE
Added a missing space

### PR DESCRIPTION
**Pull request by Mailaender**
Something did not work. I assume a syntax/indention error.

### CODE REVIEW

**Comment by Mailaender** [comment]
Followup of https://github.com/dahlbyk/up-for-grabs.net/pull/119

**Comment by shiftkey** [comment]
Weird, I can't see it in the list but I also didn't think the lack of a space would be a big issue.

Let's see what happens next...

**Comment by Mailaender** [comment]
Still not there. I am pretty clueless what I did wrong.

**Comment by akoeplinger** [comment]
The issue is the `:` in `Conquer: Red`, you'll need to enclose the description in quotes or YAML thinks it's a map.

**Pull request merged**
