### PR TITLE
added sorting for tags and labels

### PR DESCRIPTION
**Pull request by juliankrieger**
Added the alphabetic sorting for labels, this time directly in projectService.js.

### CODE REVIEW

**Comment by juliankrieger** [comment]
@ritwik12 see #1106. #1106 Can be closed

**Comment by ritwik12** [comment]
@juliankrieger Thanks!!

**Review by Zarad1993 — COMMENTED** [review]
@juliankrieger - I assume by following ES6 changes in this patch there are no plans of supporting IE?

**Comment by ritwik12** [comment]
@juliankrieger I agree with @Zarad1993 and I've crossed checked too that up-for-grabs is no longer working on IE. @juliankrieger Can you please fix this issue ASAP? It's not good to have this issue open for long time.

**Comment by Zarad1993** [comment]
@ritwik12 @juliankrieger - I'll remove that in my new PR to add filters.

**Comment by Zarad1993** [comment]
Removed in #1114. **Note: Not tested on IE though as the PR is not intended to solve that.**

**Comment by juliankrieger** [comment]
@ritwik12 yeah I‘m doing it when I get home in two hours :)

**Comment by ritwik12** [comment]
@juliankrieger @Zarad1993 Working on my IE. I guess #1114 solved it.

**Comment by ritwik12** [comment]
@juliankrieger Please check on IE before working on that.

**Pull request merged**
