### PR TITLE
Delete robots.txt

### PR DESCRIPTION
**Pull request by akshaykumar2505**

### CODE REVIEW

**Comment by ritwik12** [comment]
@akshaykumar123 Hey, can you please tell me what was the use of this file and why is it not needed anymore?

**Comment by akshaykumar2505** [comment]
Its just a simple text file which is useless

**Comment by ritwik12** [comment]
@akshaykumar123 Thanks!!

**Comment by dahlbyk** [comment]
@akshaykumar123 @ritwik12 is there a specific problem with the robots.txt? It's definitely not useless:
https://moz.com/learn/seo/robotstxt.

**Comment by ritwik12** [comment]
@dahlbyk That is why I asked. I don't know it's use. Reverting back. Sorry for the trouble.

**Comment by dahlbyk** [comment]
No worries

**Comment by ritwik12** [comment]
@akshaykumar123 Please do request review and create an Issue whenever you want to delete or add something.

**Pull request merged**
