### PR TITLE
Presenting New Look 

### PR DESCRIPTION
**Pull request by Jai2305**
### Netlify preview 
image
image

### CODE REVIEW

**Comment by Jai2305** [comment]
@ritwik12  I think it should be good to go for now , I request a review from your side , please feel free to message if any changes required

**Comment by ritwik12** [comment]
@Jai2305 Looks great to me. nice work over there. No bugs for me yet. I will leave it for a few days for @shiftkey to have a look at it. He might be busy as per his status. Will merge this if he is not available for feedback in few days.

**Comment by ritwik12** [comment]
@Jai2305 I think we are good to merge this for now. @shiftkey might suggest improvements or changes once he will be back

**Comment by ritwik12** [comment]
@Jai2305 Thanks for contributing. It's a much-needed contribution.

**Pull request merged**
