### PR TITLE
Markdown-ify the project description

### PR DESCRIPTION
**Pull request by zuta**
Added Markdown support for the project description.

Used showdown lib to parse markdown to HTML: https://github.com/showdownjs/showdown

Ref: https://github.com/up-for-grabs/up-for-grabs.net/issues/288

P.S. I'm noob

### CODE REVIEW

**Comment by zuta** [comment]
Here is a screenshot:

pr

**Comment by shiftkey** [comment]
This seems pretty great, @ZuTa - thanks for taking a shot at it! I had a quick skim to see if there was a way for us to do this server-side (so we can avoid the client side dependency completely), but couldn't spot anything easy to use - Jekyll doesn't give us the right hooks to parse markdown inside a template, but perhaps I'm missing something?

Thoughts @dahlbyk @jrusbatch?

**Comment by zuta** [comment]
@shiftkey haven't worked with Jekyll before, so decided to go with the approach I'm most comfortable with. 

Thanks for getting back to me so fast.

**Comment by shiftkey** [comment]
Just noticed that GitVersion is already inlining a link - let's switch that over to Markdown while we're in here https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/gitversion.yml#L2

**Comment by zuta** [comment]
The result of switching over to Markdown.

Before:
git2

After:
git1

**Comment by zuta** [comment]
ping

**Comment by shiftkey** [comment]
This all seems fine - there's just a merge conflict with this branch that's preventing me merging it.

cc @dahlbyk @jrusbatch to get a :thumbsup: before merging it in

**Comment by zuta** [comment]
@shiftkey fixed merge conflict. Should be good to go.

**Comment by shiftkey** [comment]
Alright, I'm gonna take this in. Thanks @ZuTa!

**Comment by dahlbyk** [comment]
Belated :+1:

**Pull request merged**
