### PR TITLE
improving frontend

### PR DESCRIPTION
**Pull request by jitendraKhadoliya**
Hello everyone,

"improving fronted"

I have recently made some significant changes to the web app, including the addition of a media query that has greatly improved its overall UX friendliness. Specifically, I have ensured that both buttons are now the same size and have the same height from the top and bottom, resulting in a more professional appearance. Additionally, I have ensured that both buttons are on the same line, giving the app a more impressive look. I have also ensured that the margin right is consistent across both buttons and have fixed the problem of the overlay on the text field.

I believe these changes will make a real difference to the web app's user experience, and I would like to invite all of you to contribute to this pull request by reviewing and providing your feedback. Your thoughts and suggestions are always valuable, and I look forward to hearing your feedback on this update.

Thank you for your time and consideration, and I am looking forward to working with you all on this pull request.
127 0 0 1_4000_(iPhone SE)

### CODE REVIEW

**Comment by AllanOcelot** [comment]
Nice little fix,

I've reviewed the CSS and it looks fine to me - however, cannot approve nor confirm it works as expected locally due to time constraints, so requesting someone else test this locally to ensure it works as expected.

**Comment by shiftkey** [comment]
There's a Netlify environment open with each PR that you can test these changes out on: https://deploy-preview-3828--up-for-grabs-test-bench.netlify.app/

**Comment by jitendraKhadoliya** [comment]
> Nice little fix,
> 
> I've reviewed the CSS and it looks fine to me - however, cannot approve nor confirm it works as expected locally due to time constraints, so requesting someone else test this locally to ensure it works as expected.

I made changes only in the CSS file it will not affect on any another thing
 locally it's working fine
brother @shiftkey also tested it 
merging this will not create any mess

**Review by shiftkey — APPROVED** [review]
Thanks for the contribution @jitendraKhadoliya!

**Comment by jitendraKhadoliya** [comment]
Hey @shiftkey   and @AllanOcelot ,

I just wanted to take a moment to thank you both for helping me with my first open-source contribution to GitHub. It was a really special moment for me, and I'm so happy to have been able to make a positive contribution to the community. This being my first open-source contribution, it was a great learning experience, and I won't forget it for my entire life.

thank you again

**Comment by AllanOcelot** [comment]
Anytime @jitendraKhadoliya  welcome to the community! Thanks for making Up For Grabs better!

**Comment by MyAssistantSDK** [comment]
> Hello everyone,
> 
> "improving fronted"
> 
> I have recently made some significant changes to the web app, including the addition of a media query that has greatly improved its overall UX friendliness. Specifically, I have ensured that both buttons are now the same size and have the same height from the top and bottom, resulting in a more professional appearance. Additionally, I have ensured that both buttons are on the same line, giving the app a more impressive look. I have also ensured that the margin right is consistent across both buttons and have fixed the problem of the overlay on the text field.
> 
> I believe these changes will make a real difference to the web app's user experience, and I would like to invite all of you to contribute to this pull request by reviewing and providing your feedback. Your thoughts and suggestions are always valuable, and I look forward to hearing your feedback on this update.
> 
> Thank you for your time and consideration, and I am looking forward to working with you all on this pull request. 127 0 0 1_4000_(iPhone SE)

**Pull request merged**
