### PR TITLE
[WIP] render list of projects server-side to support clients who disable JavaScript

### LINKED ISSUE #511: Visiting the site with javascript disabled does not display any projects
Hey!

I just wanted you to know, that if I visit the site ([link](http://up-for-grabs.net/#/)) with javascript disabled, only the static content is displayed, no projects are listed, and no message informing the user that the site requires javascript is displayed.

This could be useful, whenever a user of noscript visits the site.

### PR DESCRIPTION
**Pull request by mrtnmgs**
Fixes #511

Hi,
Not sure why the diff is highlighting the last line (44)... Does it matter?

### CODE REVIEW

**Comment by ritwik12** [comment]
#511

**Comment by ritwik12** [comment]
@mrtnmgs I don't think that matters

**Comment by ritwik12** [comment]
@mrtnmgs Thanks for your PR, I'll wait for other's reviews on this.

**Comment by shiftkey** [comment]
> Not sure why the diff is highlighting the last line (44)... Does it matter?

That change is indicating that there was no line-ending in the file, but this PR adds it. This is fine.

**Comment by shiftkey** [comment]
The only problem I have with this PR is it's impact on downloading the `index.html` file.

Currently, the file is ~70kB gzipped (260kB uncompressed):



With this change, it's ~140kB gzipped (860kB uncompressed



I'm somewhat onboard with this idea to show something when JS is disabled, but it feels excessive to send down that much data for everyone (we're already embedding the projects list as JS).

I had a look at what percent of users are browsing with JS disabled, and [one survey](https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/) claimed ~1%.

Anyway, the site is up at https://deploy-preview-1079--up-for-grabs-test-bench.netlify.com/ if others would like to play around with this and suggest other ideas.

**Comment by shiftkey** [comment]
After being able to embed stats in the build in #1346 I came back to this and realised we had a simpler solution available - render a random subset of projects inline, complete with stats.  This required some work to make Jekyll choose a random sample of projects, because I didn't want to list them all until I got a better idea of how we'd tackle pagination now that we're at ~800 projects.

@mrtnmgs thanks for opening this PR. Hopefully after that new PR lands we can figure out ways to refine the experience.

**Pull request closed without merging**
