### PR TITLE
change primary colour for headers and links

### PR DESCRIPTION
**Pull request by tstathara**
change main color

### CODE REVIEW

**Comment by ritwik12** [comment]
@tstathara  Please share a preview for this

**Comment by shiftkey** [comment]
> Please share a preview for this

@ritwik12 every PR that gets opened here has a corresponding Netlify staging site created (if the site builds successfully): 



The `Details` link here will show you what you're looking for.

To illustrate the color change, I went to [this site](https://www.colortools.net/color_compare_colors.html) and put them side-by side:



@tstathara are you able to elaborate on why you chose this colour? I'm really hazy on the context, and the staging site seems nice, but I'd love to understand the context more before merging...

**Comment by tstathara** [comment]
It is the color from the image in header. It is darker, i find it better

**Comment by shiftkey** [comment]
@tstathara looking at the [deploy link](https://deploy-preview-1391--up-for-grabs-test-bench.netlify.com/#/) I can see there's a banner in the top-right that still has the old colour (or similar) for it's background:



That seems to be coming from this value:

https://github.com/up-for-grabs/up-for-grabs.net/blob/f8bad195299233ea224d23ae70ab1ab0171ad06f/stylesheets/stylesheet.css#L150

Are you interested in also updating that style?

**Comment by tstathara** [comment]
of course!

**Comment by shiftkey** [comment]
Having stared at this a bunch over the previous week, I'm still a fan of what we have currently with the two slightly different blues. In particular it gives the banner some depth:



Contrasting with what's proposed in this PR, it feels more one-dimensional and less like a banner:



And the blue we use currently looks more brighter when it's used a lot in the project list:



Switching that over to the darker blue feels a bit heavier:



My design skills are not great, so I don't really have any good advice about how to make this better, but I'm currently feeling like I prefer the current colour scheme over what's proposed by this PR. I wish I felt differently @tstathara!

Going to let this sit until Wednesday to see if anyone else has differing opinions on this.

**Comment by ritwik12** [comment]
@tstathara @shiftkey I prefer the current bright one, don't see a need to switch to dark.

**Comment by shiftkey** [comment]
Closing this out as we prefer the current colour scheme.

Thanks for the contribution @tstathara!

**Pull request closed without merging**
