### PR TITLE
Adding FakeItEasy

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by shiftkey** [comment]
Ugh, merge conflict...

**Comment by blairconrad** [comment]
Competing projects submitted PRs? I'll rebase.

**Comment by blairconrad** [comment]
Thanks for your understanding.

**Comment by shiftkey** [comment]
@blairconrad thanks for rebasing!

**Comment by blairconrad** [comment]
Thank you!

**Comment by dahlbyk** [comment]
We should put a tip somewhere that adding at a random location in the file will make it less likely to conflict. :)

**Comment by adamralph** [comment]
Thanks guys!

**Comment by shiftkey** [comment]
> We should put a tip somewhere that adding at a random location in the file will make it less likely to conflict. :)

Crazy idea - would it be possible to split this monolithic file into smaller files (named based on the project) which are then combined at build or runtime? That'd make the conflicts a non-issue.

**Comment by dahlbyk** [comment]
I like crazy ideas. :arrow_up:

**Pull request merged**
