### PR TITLE
Presenting New Look

### PR DESCRIPTION
**Pull request by Jai2305**
# In response to Improving Frontend  #930
### Changed the front-end for
- Better use of space 
- Neat  and Responsive

### In Light Mode
- 1) image
- 2) image

### In Dark Mode
- 1) image
- 2) image

### CODE REVIEW

**Comment by Jai2305** [comment]
I closed the previous pull request and made some changes , I am not sure what is causing the checks to fail, any help will be appreciated, I think they are because of merge conflicts but I am not sure .

**Comment by ritwik12** [comment]
@Jai2305 I resolved those merge conflicts for you.

**Comment by ritwik12** [comment]
@Jai2305 Can you please check your changes? I am not able to see content on https://deploy-preview-3146--up-for-grabs-test-bench.netlify.app/ which is your netlify deployed version of the PR. Also, the dark/light mode button is showing twice. See this for reference.

Screen Shot 2022-03-31 at 12 01 11 PM

**Comment by Jai2305** [comment]
@ritwik12  Thank you for resolving conflicts , I did not resolve them because I just needed a GO signal from your/authorities side 
But yeah as for the problems I will take a look into it , as in my local server it is working perfectly, I am not sure how 
https://deploy-preview-3146--up-for-grabs-test-bench.netlify.app/  works for deploying the code , the double images are maybe because I added the images in the pr once again so maybe the system is taking both the images the once which is in PR and another which may automatically be at the https://deploy-preview-3146--up-for-grabs-test-bench.netlify.app/  side , also for content visibility maybe https://deploy-preview-3146--up-for-grabs-test-bench.netlify.app/  is expecting table but there is no table now , only divs , again I am not sure how this is rendering it but I will take a look into it , If you have any insight on it , it will be very much appreciated  .

**Comment by ritwik12** [comment]
@Jai2305 The way netlify works is similar to having your new code merged with the existing code and deploy it.

Netlify uses the changes in PR and deploy as a whole to show how it will look or work once merged. For eg: Take any PR where someone is just adding their project to the list.

When you will click on deploy/netlify which is just above merge button on the PR, you will see a new deployed version of up-for-grabs where the newly added project is also in the list.

**Comment by Jai2305** [comment]
Ohh... got it !  I think the obvious solution is that I have to rebase my PR onto the one that netlify is using , and see what are the changes against it , which are causing the problems, it is possible that my local repository of that branch was not up to date , for eg , I remember adding the dark mode pictures once again , which I think caused the logo to appear twice , once from the header , once from the body 
So please tell me the branch which netlify is using to merge PRs against and create the simulation. In simple words I just want to know what is the existing code .. Thanks @ritwik12

**Comment by ritwik12** [comment]
@Jai2305 just do `git pull --rebase`. It should sort it.

**Comment by ritwik12** [comment]
Netlify is working on gh-pages branch of the upstream.

**Pull request closed without merging**
