### PR TITLE
Added the NUnit test framework

### PR DESCRIPTION
**Pull request by rprouse**

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks!

**Comment by rprouse** [comment]
That was quick @shiftkey, thanks.

**Comment by daveaglick** [comment]
That was unnaturally fast. Is the ability to see PRs before they're actually sent some new feature GitHub emplyees are testing?

**Comment by rprouse** [comment]
@daveaglick, I am pretty sure that @shiftkey merged my pull request before I submitted it :laughing:

**Comment by shiftkey** [comment]
@rprouse @daveaglick looking at the timestamps on the first and second comments, I count approximately 45 seconds between them.

Don't worry, I don't have those sorts of superpowers. Or do I?

**Comment by shiftkey** [comment]
[Knowing when someone forks a repository kinda helps](https://twitter.com/rprouse/status/679104186932416512) :grin:

**Comment by daveaglick** [comment]
TMI. That's like learning Batman is just some dude with a fancy car. I liked the mystery better.

**Comment by rprouse** [comment]
LOL, that IFTTT script was intended to announce exciting new projects I create, not random forks. I guess I should start creating more exciting new projects or turn it off.

**Pull request merged**
