### PR TITLE
updated wording on last bullet list inside of Readme.md

### PR DESCRIPTION
**Pull request by batistaDev1113**
Please, let me know if you have any questions or if there is anything else I can help with!

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks for your contribution! It is the great spirit of open source to help others.

This particular PR adds no value to the project and is distracting for maintainers who are busy solving real problems. We will not merge it to keep our Git history simple and reduce clutter.

However don't let this discourage you from making more valuable contributions in the future. With more time investment you can hopefully dive deeper, do your homework, understand the projects and make contributions that are actually valuable. As always, mastery requires practice so you'll need to be persistent, learn and invest time before you'll start noticing progress. However this is very rewarding and if done right prepares you for a fun, interesting and fulfilling lifetime in open source. Sending simple PRs like these is a great first step to practice. Being an open-source contributor also improves your chances of finding a good job that recognizes your contributions.

All the best and good luck!

**Comment by batistaDev1113** [comment]
Hi @shiftkey ,

I understand if you do not think this contribution has any meaning but I do not need your sermon.  I did not get a bachelor in computer science thanks to you.  I know what being persistent and work hard means.  I just came across your repo for the first time and noticed the wording on that last bullet list a little repetitive and so I thought it would sound better: my personal opinion.  I thought contributing meant to help in any possible way and not only on BIG things.  I guess I will have to keep in mind how big the problem is in your repo if I want to contribute ibn the future!  You are saying that sending simple PR like these are a great first step to practice but in reality, it could keep people away from actually wanting to contribute to your repo if they are met with a sermon as if they have never coded before, just because their PR was "simple".

**Comment by shiftkey** [comment]
@batistaDev1113 apologies for the canned reply I borrowed from another maintainer - it wasn't my intent to demean your contribution. I'm just exhausted at the moment and have been buried in Hacktoberfest contributions already and wanted to save time. 

I do appreciate the effort here, but I just couldn't see the original issue which is probably why I didn't reply initially to #2344.

Best of luck with your open source journey.

**Comment by batistaDev1113** [comment]
Np! I understand, and thank you!

**Comment by ritwik12** [comment]
@batistaDev1113 Sorry for all this but due to HacktoberFest we are getting tons of PRs which are just to increase the counts to complete HacktoberFest. I am exhausted with so many PRs and it feels really bad when we get a PR which is just for the purpose of COUNT. I felt what you meant and it was our bad to consider you into that bad crowd. But believe me, it is like a flood in October here at up-for-grabs and also my other personal Repos. HacktoberFest is meant to make people start with OpenSource and stick to it but we have all types of people who misuse it.

No matter how small a contribution is it is always counted. I started with editing README.md for a few starting PRs as I couldn't find much to contribute to other than that. But I stick to it and in some time I was able to find projects where I was able to learn and contribute too. 

I am writing this just because my initial PRs were "simple" too. Please do contribute again!!

**Comment by batistaDev1113** [comment]
Hi @ritwik12,

I appreciate the apologies!  No worries, is all water under the bridge now.  Just a simple clarification: if you notice, my PR was two days ago and Hactoberfest did not begin until today.....meaning that I did not get any credit for this.  I did it because I felt like doing that contribution(whatever small it was).  On the other hand, I get how stressful this time of the year could be for you guys as admin on a repo, and the skepticism about small contributions and the reason behind them.

Anyways, all good now and I will definitely contribute in the future to the repo.

Thank you!

**Comment by ritwik12** [comment]
@batistaDev1113 Understood that. Thanks!!

**Pull request closed without merging**
