### PR TITLE
Update publiclab.yml

### PR DESCRIPTION
**Pull request by jywarren**
Changed newcomer issues listing URL to a friendlier and more organized https://github.com/publiclab/plots2/projects/2

### CODE REVIEW

**Comment by shiftkey** [comment]
@jywarren this is a really cool trick!

It's going to hurt the issue count listing on the main site, but I can open an issue to see what we can do about this independent of this PR.

Let me know if you want me to merge this...

**Comment by shiftkey** [comment]
cc @dahlbyk @jrusbatch for :eyes:

**Comment by jywarren** [comment]
Yeah, just trying this out... ok - i wasn't sure if the count was going to be drawing on the issues link. Maybe we hold off on merging for now, and think about a way to have both an issues list link and a clickable link?

**Comment by shiftkey** [comment]
Closing this out for now - @jywarren could you open an issue about what you would like to see enhanced here, so we can discuss things. Here's our discussion on supporting multiple labels, for example #240

**Pull request closed without merging**
