### PR TITLE
Change label for GitLab CE to "Accepting Merge Requests".

### PR DESCRIPTION
**Pull request by adamniedzielski**
We changed our contributing policies for GitLab CE - see
https://gitlab.com/gitlab-com/www-gitlab-com/merge_requests/4080.

### CODE REVIEW

**Comment by shiftkey** [comment]
@adamniedzielski thanks!

**Comment by waldyrious** [comment]
Shouldn't the link use `weight=1`, per the description in the merge request linked above? I.e. https://gitlab.com/gitlab-org/gitlab-ce/issues?assignee_id=0&label_name[]=Accepting%20Merge%20Requests&weight=1

**Comment by rymai** [comment]
@waldyrious `weight=1` is for first-timers. ;)

**Comment by waldyrious** [comment]
@rymai isn't that precisely the scope of up-for-grabs.net? From the [homepage](http://up-for-grabs.net):

> This is a list of projects which have curated tasks specifically for new contributors.

@shiftkey perhaps this sentence could be used in this repo's description here on github, since it's clearer than the current "Jump in!" -- what do you think?

**Comment by adamniedzielski** [comment]
@waldyrious I believe that:

> This is a list of projects which have curated tasks specifically for **new contributors.**

"New contributors" means "new contributors to GitLab codebase".

First timers (as in http://www.firsttimersonly.com/) means "new contributors to any open source project ever".

Does it make more sense now?

**Comment by waldyrious** [comment]
Hmm, I think I get it:

- "new contributors to GitLab codebase" --> label="Accepting Merge Requests" + weight: <5
- "new contributors to any open source project ever" --> label:"Accepting Merge Requests" + weight:1

Is this correct?

**Comment by adamniedzielski** [comment]
@waldyrious Yes, that's correct!

**Comment by waldyrious** [comment]
In that case, maybe the link could use `weight:<5` (assuming that's the correct syntax)?

**Pull request merged**
