### PR TITLE
Add CFEngine

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by ritwik12** [comment]
@nickanderson Please correct file extension from .yaml to .yml, tests are failing because of that.

**Comment by nickanderson** [comment]
I don't understand the travis build failure here.

... Page hadn't refreshed yet. Will do.

**Comment by nickanderson** [comment]
File renamed, squashed.

**Comment by ritwik12** [comment]
@niccokunzmann Your file extension which was .yaml was the reason for Travis failure. It's fine now.

**Comment by ritwik12** [comment]
@nickanderson Thanks!!

**Comment by nickanderson** [comment]
Thank you!

**Pull request merged**
