### PR TITLE
Add my project gtrending

### PR DESCRIPTION
**Pull request by hedyhli**

### CODE REVIEW

**Review by ritwik12 — CHANGES_REQUESTED** [review]
@hedythedev There are no currently open issues for the Label you provided in the project repo. please add some issues or use some other label so that contributors can work on the issues

**Comment by hedyhli** [comment]
OK, i will. Thanks for reminding me. By the way what's the difference between the labels needs work and needs tasks?

**Comment by ritwik12** [comment]
@hedythedev `Needs tasks` mean needs ISSUES for contributors to work on and `Needs work` is used if there is something wrong or missing in PR. That is my understanding of those too.

**Comment by hedyhli** [comment]
@ritwik12 done

**Review by ritwik12 — APPROVED** [review]
LGTM!!

**Comment by ritwik12** [comment]
@hedythedev Thanks!!

**Pull request merged**
