### PR TITLE
Styling update

### PR DESCRIPTION
**Pull request by AllanOcelot**
Hey gang,

I've just done some simple styling, let me know if this is the right direction and I'll work on some more 'advanced' tweaks I'd like to do to bring some life to the site. I think if the site looks more polished, more users will continue their open source journey - and that's our end goal <3.

( Let me know if anything is off with formatting / branch names etc as this is my first PR on this project )

### CODE REVIEW

**Comment by AllanOcelot** [comment]
@shiftkey  - can you look at this when you have time please?

**Comment by ritwik12** [comment]
@AllanOcelot Thanks for your PR, can you add some screenshots or video of your work? It will be easy for us that way.

**Comment by AllanOcelot** [comment]
Sure thing @ritwik12  , please find screenshots of the changes here:

https://imgur.com/a/H8m4Ky3 

👍

**Comment by ritwik12** [comment]
@AllanOcelot  That's good, but I would like you to add more things to it. There's a  lot to be improved. It will be good if we have a good design.
See #930

**Review by shiftkey — COMMENTED** [review]
The changes look reasonable, but there's a merge conflict with the `Popular tags` change in #1121 that need  to be merged into this PR. @AllanOcelot are you able to get that in and refresh the screenshots?

**Comment by AllanOcelot** [comment]
Closing in favour of the newer styling update.

**Pull request closed without merging**
