### PR TITLE
Create Potential-gifts

### PR DESCRIPTION
**Pull request by ghost**
I hope this tiny mysql project follows up-for-grabs rules.

### CODE REVIEW

**Review by ritwik12 — DISMISSED** [review]
@bacloud14 File extension of your file should be .yml. 

> _data/projects/Potential-gifts.yml

>

**Comment by ritwik12** [comment]
> I hope this tiny mysql project follows up-for-grabs rules.

Once **Linus torvalds** thought the same about Linux, now we all are using it. Nothing is Tiny!!

**Comment by ghost** [comment]
Is it just the file name that blocks merge?

**Review by shiftkey — APPROVED** [review]
Thanks for the contribution @bacloud14!

**Comment by ghost** [comment]
Many thanks..

**Pull request merged**
