### PR TITLE
Elevator Pitch

### LINKED ISSUE #4: Write some words about getting involved as a maintainer
TODO: make good words

### PR DESCRIPTION
**Pull request by shiftkey**
Resolves #4 and #3 

I wanted it to be relatively simple, but also with some details around the process. Probably needs some massaging

Thoughts? @dahlbyk @jrusbatch @nikmd23 @avanderhoorn @haacked @shanselman

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Looks good to me, its simple and easy to understand. In 2 for contributors, I might be worth referencing that they could use tags (jump-in or up-for-grabs), milestones, etc.

**Comment by shiftkey** [comment]
@avanderhoorn I added a mention about the tags here

**Comment by DavidBurela** [comment]
I think the wording itself is alright. I would just modify the layout.
The 99% case is going to be people in the community coming here to see what they can contribute to, and how to do it.
The 1% case will be project maintainers coming here to find how they can add their project. They will read it once and then it isn't needed again.

I would format it as:
- How to get started
- List of projects

And then move the project owners details out to another page

**Comment by shiftkey** [comment]
screen shot 2013-11-21 at 12 00 01 pm
screen shot 2013-11-21 at 12 00 18 pm

**Comment by dahlbyk** [comment]
I approve of this message. :shipit: and we can adjust language from there?

**Comment by shiftkey** [comment]
@dahlbyk it is done

**Comment by dahlbyk** [comment]
:clap:

**Pull request merged**
