### PR TITLE
Added favicon (Issue #93)

### LINKED ISSUE #93: Add a favicon
:lipstick:

### PR DESCRIPTION
**Pull request by mikecole**
Added favicon (Closes #93)

### CODE REVIEW

**Comment by mikecole** [comment]
Added robots.txt.

**Comment by mikecole** [comment]
Added README.md to excludes.

**Comment by dahlbyk** [comment]
Absurd how much noise there is to properly specify this stuff.

This icon works for me until we get around to settling on a logo...suppose we should resume #55, eh?

Thanks, Mike!

**Comment by mikecole** [comment]
For future reference when you get a permanent logo: http://realfavicongenerator.net/

**Pull request merged**
