### PR TITLE
Add Kotlin Multiplatform Scaffold

### PR DESCRIPTION
**Pull request by josharsh**
Kotlin Multiplatform Scaffold helps people incorporate Kotlin multiplatform into their projects smoothly. It is a scaffold which support Andorid, iOS and JS

### CODE REVIEW

**Comment by josharsh** [comment]
@KevM @kolektiv @nemequ Could we merge this please?

**Comment by ritwik12** [comment]
> @KevM @kolektiv @nemequ Could we merge this please?

Are you taking approvals from the project owners you are adding here?

**Comment by KevM** [comment]
I think you have the wrong Kevin.

**Comment by josharsh** [comment]
> > @KevM @kolektiv @nemequ Could we merge this please?
> 
> Are you taking approvals from the project owners you are adding here?

This is my project @ritwik12

**Review by shiftkey — APPROVED** [review]

**Pull request merged**
