### PR TITLE
Add Gratipay.com

### PR DESCRIPTION
**Pull request by rohitpaulk**
👋

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Hmm, there seems to be an issue with fetching issue counts... 

screen shot 2017-07-11 at 8 07 50 pm

Will look into it.

**Comment by rohitpaulk** [comment]
> Hmm, there seems to be an issue with fetching issue counts...

Looks like this is happening for other projects too. The error is due to GH rate-limiting, and it has already been handled with a tooltip. (Ref: https://github.com/up-for-grabs/up-for-grabs.net/issues/261) Nice! :)

screen shot 2017-07-12 at 11 41 12 pm

screen shot 2017-07-12 at 11 48 32 pm

**Comment by rohitpaulk** [comment]
Ready for review.

**Comment by shiftkey** [comment]
@rohitpaulk thanks!

**Pull request merged**
