### PR TITLE
Consistent tags

### LINKED ISSUE #1160: [Styling] Add styling to 'Tags'
At the moment we display 'Tags' as simple text links - of inconsistent sizes. 

We should aim to have tags consistent, I have in mind something like github labels - a simple rectangle with rounded corners, a background colour and an easy to read text colour.

I'll experiment with this myself, but raising it as an issue incase anyone else would like to attempt with an easy to implement feature.

### PR DESCRIPTION
**Pull request by nobodys-ghost**
These commits make the styling of the tags for individual projects consistent with the styling of the popular tags. I also adjusted the list of project tags to use `<ul>` and `<li>` elements (rather than a comma separated list of links) to make styling easier.

Fixes #1160 and part of #1170

### CODE REVIEW

**Comment by shiftkey** [comment]
This has broken the way tags are currently styled. Here's what is currently deployed:

Screenshot 2024-12-30 at 3 09 23 PM

The [preview site](https://deploy-preview-4943--up-for-grabs-test-bench.netlify.app/#/) for this PR shows the tags are now much larger:

Screenshot 2024-12-30 at 3 09 20 PM

Unless we can update these styles to bring them back to an appropriate size, I can't merge this PR.

**Comment by nobodys-ghost** [comment]
I can reduce the padding on the tags to make them display more compactly later today. If there's something else you'd rather have changed just let me know.

**Comment by nobodys-ghost** [comment]
I just reduced the padding and font size on the tags. It still takes up more space than the previous styling, but I think to a certain extent that's unavoidable without making the font tiny or having the text extend beyond the tag borders. 

Here's a picture of what it looks like now:
image

**Comment by shiftkey** [comment]
@nobodys-ghost in the spirit of iterating, I'll take this in as a starting point for refining it further...

**Pull request merged**
