### PR TITLE
Add test.io to project list

### PR DESCRIPTION
**Pull request by yavrumian**
I think test.io can perfectly fit in this concept and I'm really hoping of many PRs/issues on this project

### CODE REVIEW

**Comment by shiftkey** [comment]
@yavrumian thanks for submitting! It'd be great if there were some tasks available for new contributors to start with - is that something that you could setup before merging?

**Comment by yavrumian** [comment]
Hey, thanks for responding, where must I setup tasks?

**Comment by shiftkey** [comment]
> Hey, thanks for responding, where must I setup tasks?

If you create issues with the label in your repository, they'll be updated in our project stats periodically:

**Comment by yavrumian** [comment]
Okay, I've added one issue I think I'll be able to add more after merge

**Review by shiftkey — APPROVED** [review]

**Pull request merged**
