### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by sickwiz**
I HAVE ADDED CSS IN THE INDEX.HTML PAGE  WHICH WILL BASICALLY MAFNIFY THE SIZE OF PROJECT TEXT ON HOVER

### CODE REVIEW

**Comment by ritwik12** [comment]
@sickwiz Please rebase or pull, your fork is behind upstream.

**Comment by ritwik12** [comment]
Also, change the title of PR please

**Comment by sickwiz** [comment]
I am sorry I cannot understand.

**Comment by shiftkey** [comment]
@sickwiz this branch contains changes from #1356 which we merged earlier.

Please [update your fork](https://help.github.com/en/articles/syncing-a-fork), [cherry pick](https://stackoverflow.com/a/9339460/1363815) that second commit onto a new branch, and open a fresh pull request.

**Pull request closed without merging**
