### PR TITLE
Hipster-style

### PR DESCRIPTION
**Pull request by daveaglick**
So I was sitting around listening to Mumford & Sons and contemplating my beard, when this happened.

In all seriousness I was mainly just playing around. I realize it's a big departure from the current style, so take it or leave it as you see fit. That said, if you think there's promise here I can tidy it up and add a little extra umph (some work needs to be done on responsive support, cleaning up unused CSS, styling headers, etc.)

Here's what it looks like right now:

2015-10-28_22h41_55

### CODE REVIEW

**Comment by shiftkey** [comment]
Thanks for this!

Random thoughts: 
- I've got a bunch of words lying around about the vision (and documentation) for the site that I need to get out as a PR so that others can have a look over.
- I also had styling changes in mind, but those were far less along. Your changes will totally fit with the content and layout I was going to propose.
- The icon is definitely growing on me. But I have negligible artistic skills so what do I know?

**Comment by MaximRouiller** [comment]
@daveaglick is always playing with his beard. Be careful. It could go sentient any moment now.

**Comment by daveaglick** [comment]
@MaximRouiller and when it does, you better watch out.

Decided to go ahead and finish it up - styles should be (mostly) set, works responsively, some extra color, etc.

2015-10-29_12h36_57

**Comment by MaximRouiller** [comment]
Well tell your beard to not kill you when it takes over. Fine good work you've done there. :smile:

**Comment by shiftkey** [comment]
cc @dahlbyk @jrusbatch for feels

**Comment by shiftkey** [comment]
@daveaglick a couple of thoughts after looking at the second screenshot:
- not sure how I feel about the logo being at the top like that - do we need to show it there?
- the top banner is really nice, but the subheading banners seem kinda awkward

**Comment by daveaglick** [comment]
@shiftkey Good feedback - my initial (quick) reaction is this:

upforgrabs-mockup

Heading in the right or wrong direction?

**Comment by shiftkey** [comment]
:thumbsup: heading in a better direction

**Comment by shiftkey** [comment]
I'm _this_ close to just merging this in as a baseline for reworking the site content next week some time. If this is in a mergeable state, it's gonna be so much easier to do :wink:

cc @dahlbyk @jrusbatch

**Comment by daveaglick** [comment]
It probably needs to catch up with recent additions, especially the popular tags feature. I'm traveling today, but shouldn't be a problem getting it shaped up for a merge tomorrow.

**Comment by shiftkey** [comment]
@daveaglick no problem, just wanted to let you know I haven't forgotten about this...

**Comment by dahlbyk** [comment]
I support this change of pace. I do not support beardly contemplation.

**Comment by daveaglick** [comment]
Boom!

2015-12-01_17h28_22

**Comment by daveaglick** [comment]
Awesome! :thumbsup:

**Pull request merged**
