### PR TITLE
Introducing Dark-mode 

### PR DESCRIPTION
**Pull request by Jai2305**
# In response to issue Improving Frontend #930 
* Added Dark mode
* Responsiveness of the website maintained 
* Everything clearly visible 
* A switch for toggling to light and dark mode
* Toggle button sticks to it's position so user can switch at any point of time they want.
### Preview 
* Light mode 
image

* Dark mode
* 1 image

* 2 image

### CODE REVIEW

**Comment by Jai2305** [comment]
Hey there! , I am always looking for improvements , if you have any constructive criticism on how we can improve the look in the dark mode that I have introduced in this pull request and also the light mode , then please feel free to message it in this thread or open an issue , in my opinion ,for now ,this dark mode of the website is ready to rock ! :)

**Comment by ritwik12** [comment]
@Jai2305 That's a nice addition to the features. I checked the new version and it looks nice to me. Would like @shiftkey to share his views on this or any changes needed. happy to merge it :)

**Comment by ritwik12** [comment]
Dropping this comment to remind me to add @Jai2305 to the contributor list for CODE

**Comment by ritwik12** [comment]
> Dropping this comment to remind me to add @Jai2305 to the contributor list for CODE

Already added in #2886 for #2879

**Comment by ritwik12** [comment]
@Jai2305 Thanks!!

**Pull request merged**
