### PR TITLE
Add MEVN-CLI to the list

### PR DESCRIPTION
**Pull request by jamesgeorge007**
[Official Docs](https://mevn.madlabs.xyz)

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @ritwik12

**Comment by ritwik12** [comment]
@jamesgeorge007 Thanks!!

**Comment by jamesgeorge007** [comment]
@ritwik12 Would be great if you could show your love by leaving a :star:
Also, consider giving it a try when you're free. Love to hear your thoughts :smile:

**Comment by ritwik12** [comment]
@jamesgeorge007 That looks good, but having a good project like this requires a good explanation of its working in Readme or Docs. would love to read the working.

**Comment by jamesgeorge007** [comment]
@ritwik12 You may check out the [docs](http://mevn.madhacks.co) as well as the [wiki](https://github.com/madlabsinc/mevn-cli/wiki)

**Comment by jamesgeorge007** [comment]
As you may have noticed the project is in its early stage and you could really help us out in getting enough reach. Community participation is a key factor for a project like this.

**Comment by ritwik12** [comment]
Sure, thanks a lot. Link to Doc is broken. And it will be good to have Doc link in README

**Pull request merged**
