### PR TITLE
Add Opencast to the projects list

### PR DESCRIPTION
**Pull request by mliradelc**
Hi, I'm a commiter and maintainer of Opencast.

Opencast is a flexible, reliable, and scalable open-source video-capture, -management, and -distribution system for academic institutions, built by a community of developers from leading universities and organizations worldwide.

I would love to have our project in the list of up-for-grabs.

Best regards

Max

### CODE REVIEW

**Review by shiftkey — APPROVED** [review]
Thanks for the submission @mliradelc!

**Comment by AbsolytnaiaLove** [comment]
сб, 8 жовт. 2022, 17:34 користувач Brendan Forster ***@***.***>
пише:

**Comment by S1983tt** [comment]
who+am+iผมชื่อตะวัน

**Comment by S1983tt** [comment]
ใครใครก็พูดว่าผมคือคนบ้า

**Pull request merged**
