### PR TITLE
Add eBooker Project

### PR DESCRIPTION
**Pull request by arch-master**
I just added my project called [eBooker](https://github.com/arch-master/eBooker/). Please merge!

### CODE REVIEW

**Comment by shiftkey** [comment]
@arch-master a suggestion before I merge this: if you'd like others to get involved, having a list of tasks that can be worked on in the project is a great start. The smaller the task, and the more detailed it is, the easier it is for someone to find and understand what's involved. Make sense?

**Comment by arch-master** [comment]
@shiftkey I understand. I will do that as soon as possible. Please don't merge until I do that :+1:

**Comment by arch-master** [comment]
@shiftkey I added some tasks; will add some more later. Merge time (please)! :shipit:

**Comment by shiftkey** [comment]
@arch-master thanks!

**Pull request merged**
