### PR TITLE
Added CaliburnMicro Project Template

### PR DESCRIPTION
**Pull request by bogdanbujdea**

### CODE REVIEW

**Comment by dahlbyk** [comment]
Doesn't look like you have any issues!

**Comment by bogdanbujdea** [comment]
I'm sorry @dahlbyk, maybe I did this the wrong way, but I followed these instructions in order to add my project to the list: https://github.com/dahlbyk/up-for-grabs.net#add-your-project
From what I understood, I have to create a pull request with an .yml file which contains the details of my open-source project.

**Comment by bogdanbujdea** [comment]
I was looking for users to contribute to my project, but I think I understand now. I didn't knew that I had to have issues in order to add the project to the list, but I will add some requests for features marked with "up for grabs". Is this ok?

**Comment by shiftkey** [comment]
@thewindev yep, we'd like to make it easy for users to not only discover projects but quickly see the sorts of issues available under a project - so tagging them appropriately on the GitHub repo is totally helpful!

**Pull request merged**
