### PR TITLE
Create itreactor.yml

### PR DESCRIPTION
**Pull request by aradosz79**
IT Reactor needs a help

### CODE REVIEW

**Comment by shiftkey** [comment]
@aradosz79 thanks for submitting your project. We've not really dealt with Trello boards before so I had a look at it, putting myself in the shoes of a new contributor, to see how easy it would be to get involved.

Screen Shot 2019-09-27 at 10 13 20 AM

It's not very clear to me which items on this list are available to pick up - is it the "Todo" list, or the "Planned" list?

Digging into each item, it's also not clear what each work item entails. I picked off [the first "Planned" item](https://trello.com/c/LzM36ykD/28-redesign-the-main-page-of-the-agency) which linked to a [blog post](https://artur.jaaz.co.uk/2019/09/agency-icole-it-reactor.html) that didn't really provide much more context.

I checked [the second "Planned" item](https://trello.com/c/sqGyEw4J/15-migrate-icole-legacy-project) which had a list of things below that might be pages or something that need to be updated:



It wasn't clear to me where I find those pages, as your project link https://agency-icole.github.io/ goes to a landing site that lists a number of GitHub repositories.

In this current form, I can't merge in this project because:

 - it's not clear enough to me which tasks are available for new contributors to work on
 - the tasks available do not have enough context for someone like me to know what needs to be done and where to make the change

I am interested in the projects listed on the home page, as these might be a better fit for submitting:



Is there a project here that you think would be suitable for new contributors? I didn't click into them because I had limited time and wanted to provide feedback rather than procrastinating, but I'm happy to provide guidance if there's something there which might be a better fit for listing on Up for Grabs...

**Review by shiftkey — CHANGES_REQUESTED** [review]
Needs further discussion

**Comment by aradosz79** [comment]
Thank you for the detailed feedback! We will improve the way you could get involved in IT Reactor and each particular project we are building. 

Yes, I will try to submit each one in the coming months individually but would like to submit IT Reactor as the main entry point and the aggregator.

I will return to you in the coming weeks when Join Us page will be ready!

**Comment by shiftkey** [comment]
> but would like to submit IT Reactor as the main entry point and the aggregator.

I'd still like to either address this or close this PR out for the reasons explained above:

> * it's not clear enough to me which tasks are available for new contributors to work on
> * the tasks available do not have enough context for someone like me to know what needs to be done and where to make the change

@aradosz79 please let me know if you plan to address this for the Trello board.

> I will return to you in the coming weeks when Join Us page will be ready!

This sounds great!

**Comment by shiftkey** [comment]
Closing this out as the project doesn't fit the criteria for the site.

**Pull request closed without merging**
