### PR TITLE
Changes in Project Names & status

### PR DESCRIPTION
**Pull request by ramlaxman**
Fixes Issue #1033

### CODE REVIEW

**Comment by ritwik12** [comment]
Thanks for your PR, a small request. Can you please send this as three individual PRs so that we can keep track of things. This way things will get mixed up.

**Comment by ritwik12** [comment]
Also, please tell me why readme edit is required?

**Comment by ramlaxman** [comment]
> 
> 
> Also, please tell me why readme edit is required?

It is somewhat tough to read for beginners to understand first three lines.
For faster understanding and not spending much time on same.

**Comment by ramlaxman** [comment]
> 
> 
> Thanks for your PR, a small request. Can you please send this as three individual PRs so that we can keep track of things. This way things will get mixed up.

OK No Problem.
I will close this one.

**Pull request closed without merging**
