### PR TITLE
Create CICD-Using-Jenkins.yml

### PR DESCRIPTION
**Pull request by NishkarshRaj**
Added CICD-Using-Jenkins project.

### CODE REVIEW

**Comment by NishkarshRaj** [comment]
@shiftkey Sir please help me out for setting GitHub Actions to review the PRs. This is amazing 😄

**Comment by shiftkey** [comment]
> @shiftkey Sir please help me out for setting GitHub Actions to review the PRs. This is amazing 😄

@NishkarshRaj I'm glad you like it!

It's a long story, but my initial plans to do this from Actions were limited by [the access granted to actions running in a fork](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token) which meant I couldn't do even a small thing like add a comment to this PR.

The logic itself was reusable, so aside from re-implementing the logic for detecting when it should run, and cloning the PR into a directory where I can perform the same checks, it was basically copy-pasting into a small Heroku site that consumes webhooks.

I'll do a writeup more about it once I've tidied up and better refactored things, but there's some details in #1713 to learn more about it.

**Comment by NishkarshRaj** [comment]
> I'll do a writeup more about it once I've tidied up and better refactored things

Waiting for the writeup. But where will you share it? On your website?? 👍

**Comment by NishkarshRaj** [comment]
> but there's some details in #1713 to learn more about it.

Went through the repository 💯 . I will try to understand what it does I am still a beginner in Ruby 🙁

**Comment by shiftkey** [comment]
@NishkarshRaj the blog post will help to explain the concepts - I'm just doing it in Ruby because that's what I'm using these days and I wanted to host it on Heroku to force myself to keep it simple.

**Pull request merged**
