### PR TITLE
Add many F# repositories and update existing ones

### PR DESCRIPTION
**Pull request by StachuDotNet**
Added a *bunch* of F#-related repositories.

If/when this PR is accepted, I'll edit this comment with a link to a blog post where I explain my process (I wrote some scripts against the GitHub API to do this). Cheers!

### CODE REVIEW

**Comment by ritwik12** [comment]
@StachuDotNet Adding so many projects together in a single PR. without the permission of Repo's owner. Do you think this is fine?

**Comment by StachuDotNet** [comment]
I think it's likely far less painful than ~90 individual PRs.

**Comment by ritwik12** [comment]
But what about if any of the repo owners don't want this?

**Comment by ritwik12** [comment]
What you did is really good. but I think personally that they should have the right to decide about this. I will merge this as soon as @shiftkey or other's feel ok about this.

**Comment by StachuDotNet** [comment]
I frankly don't understand why they'd be upset. The site's power is data. I
gave a lot of data :)

**Comment by ritwik12** [comment]
@StachuDotNet It is not about getting hurt. It is about rights. Maybe you are right. It is a good thing to have your project on up-for-grabs. but not for everyone.

**Comment by ritwik12** [comment]
Let others give their reviews on this. It is not one or two projects. It's more than 90. Others review matters too. Just wait a little bit.

**Comment by ritwik12** [comment]
It's far likely easy for you to have all in one PR. But for me it is the same :sweat_smile: I have to check each and every project individually.

**Comment by sergey-tihon** [comment]
F# community is very friendly for beginners and appreciates every contribution, I think that you will not find any maintainer that that "don't want" help

**Comment by ritwik12** [comment]
@StachuDotNet  I believe you. Let's just forget about others and let up-for-grabs review. Will that be fine?

**Comment by StachuDotNet** [comment]
Makes sense to me. If a repo has the tag, then they are willing to accept
help. Still confused at the confusion :)

**Comment by ritwik12** [comment]
@StachuDotNet Sure 👍

**Comment by shiftkey** [comment]
> Adding so many projects together in a single PR. without the permission of Repo's owner. Do you think this is fine?

Personally, I don't have an issue with this for new projects that are somewhat related. It's the same amount of work either way, and our automation caught a number of common issues with submitted projects all the same.

**Comment by ritwik12** [comment]
@StachuDotNet Thanks a lot for these contributions!!

**Comment by StachuDotNet** [comment]
Thanks!

**Comment by ritwik12** [comment]
@StachuDotNet You can share the blog link which you were saying.

**Comment by StachuDotNet** [comment]
Will do! Now that this is accepted, I need to finish writing the post ;)

**Pull request merged**
