### PR TITLE
Create memstate.yml

### PR DESCRIPTION
**Pull request by rofr**
Adding memstate, a high-performance in-memory event-sourced replicated object graph engine for dotnet

### CODE REVIEW

**Comment by ritwik12** [comment]
You closed the PR and created new one, but you could have simply edited the previous one?

**Comment by ritwik12** [comment]
Also what about site?

**Comment by rofr** [comment]
yes, I closed. I couldn't edit, or rather don't know how to edit a PR using ONLY the github web site. The web site is under construction, I'm setting up the DNS at this very moment.

**Comment by ritwik12** [comment]
You can edit your same file anytime and it will automatically reflect the changes you made in your repo to your PR

**Comment by ritwik12** [comment]
Also you can just tap edit in your files changed in your respective PR and can edit from there, and you can even made changes whenever someone request changes just like I did by clicking edit above that

**Comment by ritwik12** [comment]
@rofr If your site is under development, then you should provide link to your repository in place of website url for time being. else people will not be able to reach your project.

**Comment by rofr** [comment]
yes, good idea, this is taking longer than expected. url now points to https://github.com/devrexlabs/memstate

**Comment by ritwik12** [comment]
@rofr yes, now its fine.You may change it to your website link once your site is complete.

**Comment by ritwik12** [comment]
@rofr Thanks :)

**Pull request merged**
