### PR TITLE
New proyect added. Happy Hacktoberfest 19.

### PR DESCRIPTION
**Pull request by frodrisan**
He added the "Happy Hacktobertfest 19" project by Evie Skinner.

### CODE REVIEW

**Comment by shiftkey** [comment]
@frodriguez20H thanks for the submission. With only a few days left in October I'm a bit nervous about listing the project, because it's not clear to me what will happen for the project beyond Hacktoberfest. Thoughts?

**Comment by frodrisan** [comment]
@shiftkey Greetings, I don't know if you refer yours to the added projects.
But if you mean yours, after hacktoberfest you could use it so that the people who have contributed or had in the projects punctuate or value the contribution made or the learning obtained in said project.

What do you think?

**Comment by shiftkey** [comment]
> But if you mean yours, after hacktoberfest you could use it so that the people who have contributed or had in the projects punctuate or value the contribution made or the learning obtained in said project.
> 
> What do you think?

That wasn't really my concern, so I'll rephrase my question. My concern was what happens _after_ the end of October. The site itself seems to be inspired by Octoberfest (including a countdown and other content borrowed from the main site), so does that mean it'll be considered "done" when Hacktoberfest is done?

I'm more focused on listing projects here which are focused on these goals:

 - ongoing projects, not centered around a specific event
 - projects where maintainers are interested in working closely with new contributors

It's great that this project is around for people to experiment and try out open source, but it doesn't feel like a suitable fit for Up for Grabs.

**Comment by frodrisan** [comment]
@shiftkey Okay, now if I understood the goal you wanted. Then I cancel this pull request and see if I can find a project that can really enter that list. Thanks for the explanations and sorry for the inconvenience.

**Pull request closed without merging**
