### PR TITLE
Pagination (#665) (#303)

### PR DESCRIPTION
**Pull request by layely**
Add pagination as requested with the issues #665 and #303

### CODE REVIEW

**Comment by layely** [comment]
@shiftkey @dahlbyk can you please review this PR and send feedback if something is wrong or need to be improved.

**Comment by ritwik12** [comment]
@layely Please resolve all conflicts.

**Comment by ritwik12** [comment]
@shiftkey  and @dahlbyk I need your help for this, It will be a huge change in the website.
Please have a look at its working here #665

**Comment by layely** [comment]
Hey @ritwik12 thank you for your interest in this but is this still needed ? It's like nobody is interested in it anymore ?

**Comment by ritwik12** [comment]
@layely yes it is obviously needed and your work is great.. The problem is that it is a great change and I can't decide alone. And @shiftkey might  be busy. So give them time.

**Comment by ritwik12** [comment]
@shiftkey Please have a look at this whenever you have time.

**Comment by ritwik12** [comment]
@layely Thanks :) and sorry for the late

**Comment by ritwik12** [comment]
@layely Sorry I reverted this PR after merging as it was not displaying any projects at all.Please verify your code and see if it works .Then I will be happy to merge it again

**Comment by layely** [comment]
Thank you @ritwik12 for your interest here. But I am very pressed these days so I will have a look at this later in this week.

**Pull request merged**
