### PR TITLE
 Delete eBooker.yml  

### PR DESCRIPTION
**Pull request by ramlaxman**
- Project does not exist
-  Fixes 2 from #1033

### CODE REVIEW

**Comment by ramlaxman** [comment]
Hi @ritwik12, 
Please take a look at this

**Comment by ritwik12** [comment]
@ramlaxman Please remove your masonite commit from this PR as you are already having an individual PR for that in #1040

**Comment by ritwik12** [comment]
@ramlaxman I guess you need to send a new PR or you need to delete extra commits using which you can do with `git rebase`

**Comment by ramlaxman** [comment]
> 
> 
> @ramlaxman I guess you need to send a new PR or you need to delete extra commits using which you can do with `git rebase`

Ya. I am trying to figuring out same 'git rebase'.

**Pull request closed without merging**
