### PR TITLE
adding my new project

### PR DESCRIPTION
**Pull request by Saif64**
A collection of all the necessary questions and DSA (libraries, services, editors, tools, cheatsheets, etc.) 😊 Here you can get all the codes built from scratch and leetcode solutions that I have done in Javascript. Resources are gathered from many places and pushed into a single repository so that everyone can get what they want at a glance 😄

I think this project can help a lot of people preparing their for interview as visualization and codes are given as well as leetcode
problems are given with an optimized solution.

Please give me feedback if there has been any issue with the project

### CODE REVIEW

**Comment by Collom75** [comment]
I'm confused on how to get started

**Comment by ritwik12** [comment]
@Saif64

**Comment by Saif64** [comment]
> @Saif64

This was just a simple repository to help people... I was inspired by the repos like 
- Build your own X
- 30 days of Javascript/python/Java

**Comment by shiftkey** [comment]
Closing this out as the new file is not valid YAML. 

Please submit a fresh PR if you can update the file to suit...

**Pull request closed without merging**
