### PR TITLE
And filter for tags

### PR DESCRIPTION
**Pull request by clickr**
check out the working version at https://perthhackers.github.io/up-for-grabs.net/
sorry if I got the branching wrong, I'm new to this.
addressing issue #250

### CODE REVIEW

**Comment by clickr** [comment]
Oh and I deleted the CNAME file to avoid conflicts with our repository

**Comment by clickr** [comment]
Also I didn't quite understand all the legacy code so I did the best with what I know and left the rest alone.

**Comment by cat-prices** [comment]
I noticed that it works when you type a keyword and hit enter, but not when you type the keyword and then click the item from the dropdown.

**Comment by clickr** [comment]
I won't be able to look at this for a week or so. I guess the next step is to raise an issue and write a failing test. :-)

**Comment by ritwik12** [comment]
@shiftkey I think we should close this. It's going to be more than two and a half years now and we haven't got any updates

**Comment by ritwik12** [comment]
Closing this due to lack of activity from a long time.

**Pull request closed without merging**
