### PR TITLE
Move projects from / to _data/projects/

### PR DESCRIPTION
**Pull request by swapagarwal**
A few projects were lying around at the root of the repository.
Moved them to the proper place!

### CODE REVIEW

**Review by shiftkey — APPROVED** [review]

**Comment by shiftkey** [comment]
@swapagarwal nice spot - thanks for tidying up!

**Comment by ritwik12** [comment]
@swapagarwal Even I missed it 😅

**Comment by ritwik12** [comment]
@swapagarwal Thanks!!

**Comment by swapagarwal** [comment]
Haha, open source for the win! 🎉

**Pull request merged**
