### PR TITLE
Add R6 counters YML

### PR DESCRIPTION
**Pull request by BurkusCat**
Posted my site on reddit and it really took off. Problem is, lots of people have found issues, no one to work on them :)

### CODE REVIEW

**Comment by ritwik12** [comment]
@BurkusCat Thanks!!

**Comment by ritwik12** [comment]
@BurkusCat I hope you'll get contributors for issues really soon

**Comment by BurkusCat** [comment]
Thank you! A couple of people have shown interest in making contributions which is good :)

**Comment by ritwik12** [comment]
@BurkusCat That's great.

**Pull request merged**
