### PR TITLE
Add labels filter

### PR DESCRIPTION
**Pull request by mattpotato**
This will add a filter by label option.

Preview: http://matt011.github.io/up-for-grabs.net

### CODE REVIEW

**Comment by ritwik12** [comment]
@matt011 That's an awesome contribution, happy to have it here.

**Comment by ritwik12** [comment]
@matt011 I hope it is having all the labels.

**Comment by ritwik12** [comment]
@matt011 Also, I appreciate the preview you gave for this. feel free to contribute in future.

**Comment by ritwik12** [comment]
Solves #1069

**Comment by mattpotato** [comment]
@ritwik12 Thanks! I'm new to github and this is my first ever contribution to open source.

**Comment by ritwik12** [comment]
@matt011 It's a nice to have contribution. Welcome to open source :)

**Comment by ritwik12** [comment]
@matt011  I noticed that good-first-issue and Good-first-issue are two different labels in the filter and gives the same outcome. Please correct that so that we'll have only one filter which is the exact name as the label.
Also, there are some labels such as "Good First Bugs" which are not there in any projects but is present in the filter.

**Pull request merged**
