### PR TITLE
rework JS to support testing code

### LINKED ISSUE #1149: Tags not working
Tags below a project name doesn't seem to work. Also, on clicking them the website behaves badly and filters stop working too.

Reproduction steps:

 - browse to `up-for-grabs.net`
 - click one of the links in list of projects

screen shot 2019-02-11 at 2 52 10 pm

Expected behaviour:

 - list of projects is filtered based on the tag chosen

Actual behaviour:

 - no change to listed projects

### LINKED ISSUE #1168: Add Docs for JS modules working

### LINKED ISSUE #1169: Add Jest to run tests

### PR DESCRIPTION
**Pull request by shiftkey**
This is a rather significant PR that impacts how the JS works in the app, so I plan to leave this open for a while to gather feedback and ensure we're all happy with the changes.

In a nutshell:

 -  ported current code to use [RequireJS](https://requirejs.org/) to launch and compose things in the browser (we don't have access to bundling tools in Jekyll)
 - removed explicit `<script>` tags and [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) usage as they impact testability
 - added `jest` and ported the current unit tests (with a couple of problems) to it
 - [wrote some documentation about how this all works](https://github.com/up-for-grabs/up-for-grabs.net/blob/port-app-to-use-amd/docs/client-side-scripting.md)

I also added 9d77da21 which fixed a bug I'd noticed with how tag filters work in the tests. I think it's related to #1151 and #1153 but isn't the whole solution.

Feel free to ask questions if anything is unclear or if you have ideas to build upon this. I'd also love some help testing it locally to ensure that it's not just working on my machine.

Fixes #1169 
Fixes #1168 
Fixes #1149

### CODE REVIEW

**Comment by shiftkey** [comment]
Another thing I'm experimenting with as part of this process is being able to test PR builds before merging, using Netlify:

screen shot 2019-02-11 at 12 22 32 pm

Click the link in the commit status above to see these changes on a live site, and see if you can spot any errors!

**Comment by ritwik12** [comment]
> 
> 
> Another thing I'm experimenting with as part of this process is being able to test PR builds before merging, using Netlify:
> 
> screen shot 2019-02-11 at 12 22 32 pm
> 
> Click the link in the commit status above to see these changes on a live site, and see if you can spot any errors!

This will be really useful

**Comment by ritwik12** [comment]
Solves  #1168

**Comment by ritwik12** [comment]
Includes #1169

**Review by ritwik12 — APPROVED** [review]
Looks good to me, I have added significant issues related to the work being done in this PR. This PR consists lots of things and seems good to have.

**Comment by shiftkey** [comment]
I've not heard much else in terms of feedback about this so I'm going to merge this in and see if it helps with tracing some of our issues with tags currently.

**Pull request merged**
