### PR TITLE
Create Computer-Graphics.yml

### PR DESCRIPTION
**Pull request by NishkarshRaj**

### CODE REVIEW

**Comment by NishkarshRaj** [comment]
@shiftkey I have opened an issue related to Actions in this repository. I have been working on this for long now and I am not able to resolve the issue. Can you please help me out with it?

**Comment by shiftkey** [comment]
> I have opened an issue related to Actions in this repository.

@NishkarshRaj which issue?

**Comment by NishkarshRaj** [comment]
> 
> 
> > I have opened an issue related to Actions in this repository.
> 
> @NishkarshRaj which issue?

https://github.com/NishkarshRaj/Computer-Graphics/issues/8

**Comment by NishkarshRaj** [comment]
Sir, do I have to make some changes in this PR or is it fine?

**Comment by shiftkey** [comment]
> Sir, do I have to make some changes in this PR or is it fine?

No problems that I can see, but I'm busy with some urgent things so it'll get reviewed later. Please be patient.

**Comment by shiftkey** [comment]
> Sir, do I have to make some changes in this PR or is it fine?

No problems that I can see, but I'm busy with some urgent things so it'll get reviewed later. Please be patient.

**Review by shiftkey — APPROVED** [review]

**Pull request merged**
