### PR TITLE
Add the KBSecret project

### PR DESCRIPTION
**Pull request by woodruffw**

### CODE REVIEW

**Comment by ritwik12** [comment]
@woodruffw I think you should add a direct link to your Github repository on your website.
Or you should mention your repository link instead of your website link.

**Comment by woodruffw** [comment]
@ritwik12 The "star" button below the logo on the site is a direct link to the repository.

I could add a "fork me on GitHub" ribbon or something similar, but I'd prefer not to unless that would block this PR.

**Comment by ritwik12** [comment]
@woodruffw I noticed that, It was only for convenience.

**Comment by ritwik12** [comment]
@woodruffw  Thanks :)

**Comment by woodruffw** [comment]
Thanks!

**Pull request merged**
