### PR TITLE
Add IITP-Connect to up-for-grabs

### PR DESCRIPTION
**Pull request by dr0pdb**
Add IITP-Connect to the projects

@ritwik12 Please review and merge :smile:

### CODE REVIEW

**Comment by ritwik12** [comment]
@srv-twry Hey, Is it fine for you to have a long description?

**Comment by dr0pdb** [comment]
@ritwik12 Yeah it's fine. Should i make it shorter ?

**Comment by ritwik12** [comment]
@srv-twry No, it's totally your call.

**Comment by dr0pdb** [comment]
It's fine for me :grin:

**Comment by ritwik12** [comment]
@srv-twry Thanks!!

**Pull request merged**
