### PR TITLE
pagination (#665)

### PR DESCRIPTION
**Pull request by djm158**
Went back and pulled in @layely 's code from #727 and made some modifications to hopefully get this working!

### CODE REVIEW

**Comment by ritwik12** [comment]
@djm158  Sorry again I had to revert it as it wasn't working, see this

**Comment by ritwik12** [comment]
capture

**Comment by djm158** [comment]
noticed this, sorry about that, can you pull my branch and see if this happens locally?

**Comment by ritwik12** [comment]
@djm158 Sorry but I am a little busy. is that working on your system?

**Comment by djm158** [comment]
it was when I made the PR but I'll have to look more closely and see if I can figure out what's going on. In the future I think it would be good to have a more formal review and have it tested by at least one other contributor.

**Comment by ritwik12** [comment]
@djm158 Ya that will be good. Thanks!!

**Pull request merged**
