### PR TITLE
Mentorship

### PR DESCRIPTION
**Pull request by EASTinphectiON**
Looking for mentors familiar with GitHub that want to collaborate and mentor one another in designing things that have never been created before.

Email ebodeux16@gmail.com with the subject line "collaboration"

- thanks

-EASTinphectiON

### CODE REVIEW

**Comment by EASTinphectiON** [comment]
Please allow workflows and merges

**Comment by EASTinphectiON** [comment]
Am willing to pay and for corporate legal identites as clear outline partnerships

**Comment by ritwik12** [comment]
> Please allow workflows and merges

I am not able to understand what you mean here @EASTinphectiON

**Comment by ritwik12** [comment]
> Looking for mentors familiar with GitHub that want to collaborate and mentor one another in designing things that have never been created before.
> 
> Email [ebodeux16@gmail.com](mailto:ebodeux16@gmail.com) with the subject line "collaboration"
> 
> * thanks
> 
> -EASTinphectiON

If you are looking for mentors, LinkedIn would be a better place to reach out. You can search for people with specific skills you are looking to get mentored for and also search "mentor". There are many who will be happy to help.

Here, even adding this file won't make it reachable to people. Let me know if I can help you somehow.

**Comment by EASTinphectiON** [comment]
I'm sure you could honestly help me if your willing. Seeing as your smart enough to create a program the question is are u willing and wanting to work on one with me. We will be compensated greatly when the project is finished. I can try to arrange during but that would have to be like out of my pocket and I would t cut u in on the end reward of that's the case u know?

**Pull request closed without merging**
