### PR TITLE
In response to issue #2209 Added response when no projects are displayed

### PR DESCRIPTION
**Pull request by Jai2305**
# In response to - needs to let the user know when there are no search results #2209
### Before 
* Nothing was displayed when there were no search results 
### After 
* A message is displayed which says " No projects found with that description " 

image

### CODE REVIEW

**Comment by ritwik12** [comment]
@Jai2305 Thanks!!

**Comment by ritwik12** [comment]
@Jai2305 Works fine :)

**Comment by Jai2305** [comment]
@ritwik12 
ur welcome :)

**Comment by ritwik12** [comment]
@all-contributors please add @Jai2305 for code

**Pull request merged**
