### PR TITLE
Introduce Harmonica

### PR DESCRIPTION
**Pull request by josharsh**

### CODE REVIEW

**Comment by ritwik12** [comment]
@shiftkey I am unable to see this project listed on the website at up-for-grabs.net after merging, please see if it is same for you?

**Comment by shiftkey** [comment]
@ritwik12 it's because the file was added at the root of the repository

**Comment by shiftkey** [comment]
#1381 should address this

**Comment by ritwik12** [comment]
@shiftkey My bad, I missed to check it. Thanks

**Comment by ritwik12** [comment]
@josharsh You created PR for the wrong directory, We fixed it. Just FYI

**Comment by shiftkey** [comment]
@ritwik12 @josharsh the previous PR #1372 was correct, so I suspect it was just an oversight

**Pull request merged**
