### PR TITLE
Fixed select box layout on mobile

### PR DESCRIPTION
**Pull request by daskepon**
Hi. I am using this site to find OSS that I can contribute to.

When I was viewing this site on my smart phone, I found that the layout of the site was a bit broken, so I fixed the CSS.

**Before**
スクリーンショット 2023-06-25 225231

**After**
スクリーンショット 2023-06-25 225820

### CODE REVIEW

**Comment by shiftkey** [comment]
@daskepon which browser are you testing on? I'd love to reproduce this myself so I can verify the fix, but I haven't seen it on Chrome/Safari/Firefox when using their responsive mode tools...

**Comment by daskepon** [comment]
@shiftkey Sorry for not describing the environment.
The environment I checked is below.

### Developer Tool
- Windows11 Home 22H2
- Chrome Latest ver (114)
- Dementions : iPhone 12 Pro
- Langage : Japanese

### My Android Mobile
- Pixel7
- Chrome Latest ver (114)
- Langage : Japanese

here is video capture.

https://github.com/up-for-grabs/up-for-grabs.net/assets/6374952/b867829c-657c-4ea5-b043-418b6d4b7025

my Android capture

**Comment by Jeison-Garcia** [comment]
Hi @shiftkey, I was reviewing the issue that @daskepon report and I can confirm it. As I show in the next video, this occurs when you try to select an option of the list or reload the page while using the responsive tool of Chrome, this also occurs on mobile without needed of reload the site or select an option.

<h2>My Specs</h2>
<h3>PC</h3>
<ul>
<li>Windows 11 Pro Build 22621</li>
<li>Chrome latest version</li>
<li>Language: English</li>
</ul>

<h3>Mobile</h3>
<ul>
<li>IPhone 6 plus</li>
<li>Software version 12.5.7</li>
<li>Safari latest version</li>
<li>Language: English</li>
</ul>

<h2>Proofs</h2>

https://github.com/up-for-grabs/up-for-grabs.net/assets/138708027/d7efb3fb-7d2c-4770-a4b5-134d4ca3d744

IMG_3368

I hope this could help.

**Comment by Olanma-Kalu** [comment]
How do I use GitHub I'm new

**Comment by shiftkey** [comment]
Aha, the step that I was missing was clicking into the select menu - thanks @daskepon @Jeison-Garcia for explaining the steps to me:



Confirming this branch does not stretch beyond the viewport after clicking:

Screenshot 2023-08-27 at 4 16 03 PM

**Review by shiftkey — APPROVED** [review]
Thanks for the contribution @daskepon!

**Pull request merged**
