### PR TITLE
[WIP] Styling update

### PR DESCRIPTION
**Pull request by AllanOcelot**
Hi all,

I've had a go at updating the styling on UFG - mostly to do with removing the big bulky filters, making the tags consistent.

Lots of smaller HTML + CSS tweaks in here.
I wanted to mess around with the way we display projects - Ideally looking to move to a div based markup and not a Table one - as this would allow me to make them look much nicer.

Please have a look at this PR and provide feedback, hopefully we can implement one or two ideas.

### CODE REVIEW

**Comment by AllanOcelot** [comment]
(I should also note, this is for feedback - and should be treated as a Work In Progress PR.
I'm looking for feedback so we can work as a team to tighten up the design of UFG 😄

**Comment by shiftkey** [comment]
@AllanOcelot if you rebase your branch on top of `gh-pages` and force push  you'll get a test build URL that reviewers can directly look at.

Also, please share some before/after screenshots of the changes so we can understand the details beyond the diff itself.

**Comment by ritwik12** [comment]
@AllanOcelot I've added WIP for the title of this PR to make it clear.

**Comment by ritwik12** [comment]
@AllanOcelot Please open an issue for this so that we can have multiple PRs as it will be a WIP for a long time. It will also help others to contribute easily.

**Comment by AllanOcelot** [comment]
@ritwik12  - Will do.

@shiftkey  - I tried to rebase the PR onto gh-pages and push, but have not found a generated URL where people can see my changes.

Here are the screenshots of the current build ( https://imgur.com/a/OPjd8Z9 )

**Comment by shiftkey** [comment]
> but have not found a generated URL where people can see my changes.

@AllanOcelot check out the `deploy/netlify` link in the commit status form: https://deploy-preview-1163--up-for-grabs-test-bench.netlify.com/

**Comment by ritwik12** [comment]
@AllanOcelot Tags looks good to me in the new design, but project names looks better as simple only to me.

**Comment by AllanOcelot** [comment]
@ritwik12  - I agree with you on that, I think I got carried away ahaha.

I'll edit this PR tonight and remove / re work the title styling.

**Comment by ritwik12** [comment]
@AllanOcelot Ping

**Comment by AllanOcelot** [comment]
Hi @ritwik12  - will look into this again this week, been a while since I looked over the PR :)

**Comment by ritwik12** [comment]
@AllanOcelot Sure, thanks :)

**Comment by ritwik12** [comment]
@AllanOcelot A lot of things changed here, wanna give it a shot though?

**Comment by AllanOcelot** [comment]
@ritwik12 absolutely - I'll take a fresh copy of UFG and see what improvements can be made.
Confident we can apply a subtle but fresh coat of paint :)

**Comment by ritwik12** [comment]
@AllanOcelot Thanks!!

**Comment by AllanOcelot** [comment]
Still working on this, inbetween a couple of open source project contributions at the moment, please bare with me :)

**Review by ritwik12 — CHANGES_REQUESTED** [review]
@AllanOcelot Reminder!!

**Pull request closed without merging**
