### PR TITLE
add a license this project

### PR DESCRIPTION
**Pull request by shiftkey**
This PR will likely take a while, but I'd love 75% of the people who have contributed to this project to give a :thumbsup: to this licensing.
- I've specified MIT for the logic and styling of the site because that's the license we inherited from the Jekyll template.
- The site content (all the projects) are going to be covered under Creative Commons.

I'll comment further with how to gather that feedback.

### CODE REVIEW

**Comment by shiftkey** [comment]
**Website Code:**
- [x] @dahlbyk 
- [x] @ChrisMissal
- [x] @brownhead
- [x] @Chandu
- [x] @Steven-Pingel 

If you are happy with this PR, please leave a comment to this effect:

> I hereby release all of my contributions to this project under the terms of the MIT license.

**Comment by shiftkey** [comment]
**Site Content:**
- [x] @stevedesmond-ca
- [x] @hrj
- [ ] @Haacked
- [x] @S0lll0s
- [x] @IvanSanchez
- [x] @mj1856
- [x] @pascalberger
- [x] @jdeering
- [x] @leastprivilege
- [x] @adamralph
- [x] @rolandgeider
- [x] @vlasenko
- [x] @gsvgit
- [x] @DaniilVeriga
- [x] @pablormier
- [ ] @ybur-yug
- [x] @Seddryck
- [ ] @mbaker-dev
- [ ] @abderraouf-adjal
- [x] @wolfascu
- [x] @gdi2290
- [x] @steveklabnik
- [x] @wolftune
- [ ] @thewindev
- [x] @The-Compiler
- [x] @rauhryan
- [ ] @valentinstoychev
- [x] @shana
- [x] @kentcdodds
- [x] @raphaelm
- [x] @304NotModified
- [x] @LukePulverenti
- [x] @MarcosMeli
- [x] @ChrisMissal
- [x] @giggio
- [x] @pblasucci
- [ ] @dmcclccam
- [x] @rofr
- [ ] @nosami
- [x] @rikkit
- [x] @geobmx540
- [x] @cilefen
- [ ] @jenlampton
- [x] @akoeplinger
- [x] @Maxwe11
- [x] @DamianEdwards
- [x] @JimBobSquarePants
- [x] @khellang
- [x] @kbilsted
- [x] @castarco

If you are happy with this PR, please leave a comment to this effect:

> I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by shiftkey** [comment]
- [x] @PatrickMcDonald
- [x] @basarat
- [x] @colinodell
- [x] @yannisgu
- [x] @bricelam
- [x] @navarr
- [x] @JakeGinnivan
- [x] @dubeaud
- [x] @aaroncampf
- [x] @mcraken
- [x] @nigelcharman
- [x] @blairconrad
- [x] @jdom
- [x] @alankent
- [x] @jthelin
- [ ] @hhariri
- [x] @tommarien
- [x] @franciscojunior
- [ ] @DavidChristiansen
- [ ] @AlexArchive
- [x] @MehdiK
- [x] @RichiCoder1
- [x] @nycdotnet
- [x] @davetimmins
- [x] @nulltoken
- [x] @uhaciogullari
- [x] @tugberkugurlu
- [x] @redknightlois
- [x] @magicmonty
- [ ] @gustavohenke
- [ ] @fsgit
- [x] @pedroreys
- [x] @sgwill
- [x] @Mailaender
- [x] @dsyme
- [ ] @SgtPooki
- [x] @forki
- [x] @jbrinkman
- [x] @patriksvensson
- [x] @thomasballinger
- [x] @sapiens
- [x] @haf
- [x] @flagbug
- [x] @pver
- [ ] @Chandu
- [ ] @rogeralsing
- [x] @ovatsus
- [x] @tpetricek
- [ ] @PrivateJson
- [ ] @btford

If you are happy with this PR, please leave a comment to this effect:

> I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by shiftkey** [comment]
- [x] @rmarinho
- [x] @theburningmonk
- [x] @buybackoff
- [ ] @mvriel
- [ ] @rafanoronha
- [x] @thecodejunkie
- [x] @ploeh
- [x] @mexx
- [x] @PeteGoo
- [x] @xavierdecoster
- [ ] @Xharze
- [x] @amirrajan
- [x] @mikecole
- [x] @JohnMaguire
- [x] @odinserj
- [ ] @KevM
- [x] @robdmoore
- [x] @chester89
- [x] @staxmanade
- [x] @Mpdreamz
- [x] @andreasohlund
- [x] @jtreuting
- [x] @anurse
- [x] @plioi

If you are happy with this PR, please leave a comment to this effect:

> I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by SteveDesmond-ca** [comment]
first

j/k

I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by hrj** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by johnmaguire** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by pver** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by RichiCoder1** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by wolftune** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons BY-SA 4.0 International license.

**Comment by MarcosMeli** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by xavierdecoster** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by 304NotModified** [comment]
Why creative commons and not MIT?

**Comment by wolftune** [comment]
@304NotModified The CC is for the _content_, the writings, MIT is for the _code_.

**Comment by odinserj** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by yannisgu** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by Mailaender** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by shana** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by itsjohncs** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by IvanSanchez** [comment]
I hereby release all of my contributions to this project under the terms of the [Do What The Fuck You Want To Public License](http://www.wtfpl.net/faq/). If I'm not mistaken, it's pretty much compatible with whatever flavor of CC you guys want.

**Comment by shiftkey** [comment]
@IvanSanchez yes, yes it is!

**Comment by jtreuting** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by redknightlois** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by blairconrad** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by akoeplinger** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by mikecole** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by rolandgeider** [comment]
@IvanSanchez while yes, you might have problems under some jurisdictions should you ever have to go to court, that's why it's always a good idea to use a "proven" license.

And yes, I hereby also release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by The-Compiler** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

(this is going to be fun for people watching the repo...)

**Comment by franciscojunior** [comment]
I hereby release all of my contributions to this project under the terms of
the Creative Commons license.

On Tuesday, October 13, 2015, Brendan Forster notifications@github.com
wrote:

> - @PatrickMcDonald https://github.com/PatrickMcDonald
> - @basarat https://github.com/basarat
> - @colinodell https://github.com/colinodell
> - @yannisgu https://github.com/yannisgu
> - @bricelam https://github.com/bricelam
> - @navarr https://github.com/navarr
> - @JakeGinnivan https://github.com/JakeGinnivan
> - @dubeaud https://github.com/dubeaud
> - @aaroncampf https://github.com/aaroncampf
> - @mcraken https://github.com/mcraken
> - @nigelcharman https://github.com/nigelcharman
> - @blairconrad https://github.com/blairconrad
> - @jdom https://github.com/jdom
> - @alankent https://github.com/alankent
> - @jthelin https://github.com/jthelin
> - @hhariri https://github.com/hhariri
> - @tommarien https://github.com/tommarien
> - @franciscojunior https://github.com/franciscojunior
> - @DavidChristiansen https://github.com/DavidChristiansen
> - @AlexArchive https://github.com/AlexArchive
> - @MehdiK https://github.com/MehdiK
> - @RichiCoder1 https://github.com/RichiCoder1
> - @nycdotnet https://github.com/nycdotnet
> - @davetimmins https://github.com/davetimmins
> - @nulltoken https://github.com/nulltoken
> - @uhaciogullari https://github.com/uhaciogullari
> - @tugberkugurlu https://github.com/tugberkugurlu
> - @redknightlois https://github.com/redknightlois
> - @magicmonty https://github.com/magicmonty
> - @gustavohenke https://github.com/gustavohenke
> - @fsgit https://github.com/fsgit
> - @pedroreys https://github.com/pedroreys
> - @sgwill https://github.com/sgwill
> - @Mailaender https://github.com/Mailaender
> - @dsyme https://github.com/dsyme
> - @SgtPooki https://github.com/SgtPooki
> - @forki https://github.com/forki
> - @jbrinkman https://github.com/jbrinkman
> - @patriksvensson https://github.com/patriksvensson
> - @thomasballinger https://github.com/thomasballinger
> - @sapiens https://github.com/sapiens
> - @haf https://github.com/haf
> - @flagbug https://github.com/flagbug
> - @pver https://github.com/pver
> - @Chandu https://github.com/Chandu
> - @rogeralsing https://github.com/rogeralsing
> - @ovatsus https://github.com/ovatsus
> - @tpetricek https://github.com/tpetricek
> - @PrivateJson https://github.com/PrivateJson
> - @btford https://github.com/btford
> 
> If you are happy with this PR, please leave a comment to this effect:
> 
> I hereby release all of my contributions to this project under the terms
> of the Creative Commons license.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dahlbyk/up-for-grabs.net/pull/252#issuecomment-147806539
> .

## 

Regards,

Francisco Figueiredo Jr.
Npgsql Lead Developer
http://www.npgsql.org
http://gplus.to/franciscojunior
http://fxjr.blogspot.com
http://twitter.com/franciscojunior

**Comment by DamianEdwards** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by PatrickJS** [comment]
@gdi2290 I hereby release all of my contributions to this project under the terms of the Creative Commons license.

[Tipe CMS](https://tipe.io?ref=github-comment)

**Comment by navarr** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by 304NotModified** [comment]
Thanks @wolftune 

I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by forki** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by staxmanade** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by plioi** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by PeteGoo** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by pascalberger** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by larixer** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by ovatsus** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by rauhryan** [comment]
I hereby release all of my contributions to this project under the terms of
the Creative Commons license.

**Comment by Mpdreamz** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by rofr** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

Robert Friberg
Building OrigoDB at Devrex Labs
http://devrexlabs.com/
http://about.me/robertfriberg

**Comment by alankent** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by s-ol** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by theburningmonk** [comment]
I hereby release all of my contributions to this project under the terms of
the Creative Commons license.

**Comment by jasondeering** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by chester89** [comment]
I hereby release all of my contributions to this project under the terms of
the Creative Commons license.

2015-10-13 22:11 GMT+03:00 Jason Deering notifications@github.com:

> I hereby release all of my contributions to this project under the terms
> of the Creative Commons license.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dahlbyk/up-for-grabs.net/pull/252#issuecomment-147817846
> .

## 

Yours faithfully,
Gleb

**Comment by uhaciogullari** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by khellang** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license. :+1:

**Comment by kentcdodds** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

I also want to say that I think that what you're doing is awesome. :hand:

**Comment by patriksvensson** [comment]
I hereby release all of my contributions to this project under the terms of
the Creative Commons license.

**Comment by PatrickMcDonald** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by nigelcharman** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by pblasucci** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by clupasq** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by sgwill** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by sapiens** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by davetimmins** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by chandu** [comment]
I hereby release all of my contributions to this project under the terms of the MIT license.

**Comment by jdom** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by jdeering** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

Commented under wrong username earlier.

**Comment by Maxwe11** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by buybackoff** [comment]
I hereby release all of my contributions to this project under the terms of
the MIT license.

**Comment by basarat** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by dsyme** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by flagbug** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by pedroreys** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by rmarinho** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by kbilsted** [comment]
any license is fine by me..

I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by robdmoore** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by steveklabnik** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by nycdotnet** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by DaniilVeriga** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by adamralph** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by bricelam** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by amirrajan** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by JakeGinnivan** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

Sent from my Windows Phone

**Comment by JimBobSquarePants** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by buybackoff** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by aaroncampf** [comment]
I hereby renounce all ownership of all of my contributions to this project with the sole exceptions that you can use on Creative Commons license on my work :D

**Comment by tpetricek** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by jbrinkman** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by colinodell** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by dahlbyk** [comment]
I hereby release all of my contributions to this project under the terms of the MIT license and/or the Creative Commons license.

**Comment by dahlbyk** [comment]
Added @Steven-Pingel to https://github.com/dahlbyk/up-for-grabs.net/pull/252#issuecomment-147805856 for local storage contribution.

If you are happy with this PR, please leave a comment to this effect:

> I hereby release all of my contributions to this project under the terms of the MIT license.

**Comment by dahlbyk** [comment]
> this is going to be fun for people watching the repo...

image

**Comment by analogrelay** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by mattjohnsonpint** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by Steven-Pingel** [comment]
I hereby release all of my contributions to this project under the terms of the MIT license.

**Comment by LukePulverenti** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by giggio** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by hhariri** [comment]
I hereby release all of my contributions to this project under the terms of the MIT license

**Comment by leastprivilege** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by magicmonty** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by mcraken** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

—
Regards,
Sherief Shawky.

**Comment by nulltoken** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by ploeh** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by haf** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by MehdiK** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by tommarien** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by gsvgit** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by thecodejunkie** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by shiftkey** [comment]
At this point I've got approx 89 acknowledgements and 35 awaiting reply (about 71%).

Thanks for being so quick everyone! :metal:

**Comment by andreasohlund** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by shiftkey** [comment]
@dahlbyk thanks for picking that one up, my script didn't look for PRs against that file!

**Comment by geobmx540** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by raphaelm** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by rikkit** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license

**Comment by thomasballinger** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by ChrisMissal** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by jthelin** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by junowilderness** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by dubeaud** [comment]
I hereby release all of my contributions to this project under the terms
of the Creative Commons license.

On Wed, Oct 14, 2015 at 10:44 AM, Chris McCafferty <notifications@github.com

**Comment by pablormier** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by Seddryck** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by tugberkugurlu** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by castarco** [comment]
I hereby release all of my contributions to this project under the terms of
the Creative Commons license.

2015-10-14 18:54 GMT+02:00 Tugberk Ugurlu notifications@github.com:

> I hereby release all of my contributions to this project under the terms
> of the Creative Commons license.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dahlbyk/up-for-grabs.net/pull/252#issuecomment-148114870
> .

## 

################################################################

# 

# Andreu Correa Casablanca

# Twitter : @castarco

# Github  : https://github.com/castarco/

# Phone   : +34 669 651 292

# Website : http://litipk.com

# Blog    : http://labs.viricmind.org

# 

################################################################

**Comment by mexx** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Comment by shiftkey** [comment]
We're now at 101/124 people (81%) who have signed off on this, so I'm going to merge it in.

Thanks everyone for getting to this so quickly!

**Comment by jenlampton** [comment]
I hereby release all of my contributions to this project under the terms of the Creative Commons license.

**Pull request merged**
