### PR TITLE
Added Fluent NHibernate to the list

### PR DESCRIPTION
**Pull request by chester89**
- Fluent NHibernate

### CODE REVIEW

**Comment by dahlbyk** [comment]
Does Fluent NH have a tag (e.g. up-for-grabs) specifically to identify issues that would be a good place to start?

**Comment by chester89** [comment]
No, it doesn't - not yet. Will add one soon.

2013/11/21 Keith Dahlby notifications@github.com

> Does Fluent NH have a tag (e.g. up-for-grabs) specifically to identify
> issues that would be a good place to start?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dahlbyk/up-for-grabs.net/pull/9#issuecomment-28996762
> .

## 

ó Õ×ÁÖÅÎÉÅÍ,
þÅÒÍ£ÎÎÏ× çÌÅÂ,
ÔÅÌ. (916) 314-9324

**Comment by dahlbyk** [comment]
> Will add one soon.

Once that's done go ahead and update this PR with a new link.

**Comment by dahlbyk** [comment]
Note that the project list has been moved - if you'd still like to be listed, please update this PR to use the new format. You can just `push --force` over your existing branch.

**Comment by chester89** [comment]
OK, I created a new PR, closing this one

**Pull request closed without merging**
