### PR TITLE
Add Hexagon to the projects list

### PR DESCRIPTION
**Pull request by jaguililla**
* https://github.com/hexagonkt/hexagon
* https://github.com/hexagonkt/hexagon/projects/1

### CODE REVIEW

**Comment by jaguililla** [comment]
@ritwik12 I updated the tasks list URL. It is pointing to the Github's project with the board for the current milestone (not to the issues tab). If there is any problem with this, please tell me and I will change it. Thanks!

**Comment by ritwik12** [comment]
@jaguililla From my side it will be better if it points to issues.

**Comment by jaguililla** [comment]
@ritwik12 Changed!

**Comment by ritwik12** [comment]
@jaguililla Thanks :)

**Comment by jaguililla** [comment]
@ritwik12 Thanks to you :)

**Pull request merged**
