### PR TITLE
Adding RawCMS project

### PR DESCRIPTION
**Pull request by zeppaman**

### CODE REVIEW

**Comment by zeppaman** [comment]
there is something on my side that I can do to fix the build?

**Review by ritwik12 — CHANGES_REQUESTED** [review]
@zeppaman Please change file extension to .yml

**Comment by zeppaman** [comment]
@ritwik12 I changed the extension. Let me know if I can do anything else.

**Review by ritwik12 — APPROVED** [review]

**Comment by ritwik12** [comment]
@zeppaman Thanks!!

**Pull request merged**
