### PR TITLE
Minor modifications to improve SEO and semantics of site

### PR DESCRIPTION
**Pull request by es-rene99**
Modifications made: 
- Extended meta description
- Refactored lists like ```<ol>``` and ```<ul>``` elements nested inside ```<p>```, following https://validator.w3.org/
- Added semantic HTML5 tags

I did my test, this should not break any part of the site, but please let me know if there's room for improvement!

### CODE REVIEW

**Comment by itisdb** [comment]
Is this open for contributions?

**Comment by Meedhaa** [comment]
Is this open for contributions?

**Comment by ritwik12** [comment]
@Meedhaa Yes, you can take it up

**Comment by ghost** [comment]
> Modifications made:
> 
> * Extended meta description
> * Refactored lists like `<ol>` and `<ul>` elements nested inside `<p>`, following https://validator.w3.org/
> * Added semantic HTML5 tags
> 
> I did my test, this should not break any part of the site, but please let me know if there's room for improvement!

Keep in mind that Google says that a site's meta description does not directly affect rankings, although it can indirectly improve them by improving click-through rate.

**Comment by ghost** [comment]
I will be implementing this in my changes for #930

**Comment by ghost** [comment]
Added in #3023

**Review by ashu1230 — APPROVED** [review]
in this code we are solve the problem

**Review by Precha24 — APPROVED** [review]
Good, thanks

**Comment by shiftkey** [comment]
Because there are conflicts to resolve and the fork has been removed I've had to move this over to a new pull request https://github.com/up-for-grabs/up-for-grabs.net/pull/4129

**Pull request closed without merging**
