### PR TITLE
add Angular Full-stack Generator

### PR DESCRIPTION
**Pull request by Awk34**

### CODE REVIEW

**Comment by shiftkey** [comment]
@Awk34 are there some more relevant keywords that could be added to the list?

**Comment by Awk34** [comment]
I'd there a full list of supported keywords?

**Comment by shiftkey** [comment]
@Awk34 it's a free-form list, but you can see what others have defined on the [up-for-grabs](http://up-for-grabs.net/) site:

**Comment by Awk34** [comment]
@shiftkey how's that?

**Comment by shiftkey** [comment]
@Awk34 great, thanks!

**Pull request merged**
