### PR TITLE
Added Restful Routing

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
We could use anybody that is interested in the project. We are currently looking for someone to implement the same fluent interface to work with WebAPI.

### CODE REVIEW

**Comment by dahlbyk** [comment]
Can you add an up-for-grabs or similar label to stevehodgkiss/restful-routing#65, and update this PR to link to the label? You might also provide a few pointers in that issue to help someone new to the project get started.

**Comment by khalidabuhakmeh** [comment]
done

**Comment by dahlbyk** [comment]
Cool - can you update this PR on latest, with the new link?

**Comment by dahlbyk** [comment]
Note that the project list has been moved - if you'd still like to be listed, please update this PR to use the new format. You can just `push --force` over your existing branch.

**Comment by dahlbyk** [comment]
How meta... marking this as `up-for-grabs` if someone else wants to tackle it.

**Pull request closed without merging**
