### PR TITLE
the groundwork for reworking the site

### PR DESCRIPTION
**Pull request by shiftkey**
This extracts the index page into a number of reusable components.

I figure getting this in before going head-on into the content and layout is a better approach :metal:

### CODE REVIEW

**Comment by shiftkey** [comment]
:no_entry_sign: I think I broke the `{sites.data ...}` secret sauce with this. Please don't merge it just yet.

**Comment by shiftkey** [comment]
Pushed the merged branch here http://shiftkey.github.io/up-for-grabs.net/ and I can see it's deployed with some comment I just pushed

screen shot 2015-10-08 at 5 47 17 pm

**Comment by shiftkey** [comment]
Ready for review

**Comment by dahlbyk** [comment]
:100:

Trying very hard to forget that it's been nearly 20 years since I started using [SSI](https://en.wikipedia.org/wiki/Server_Side_Includes). Oy.

**Comment by shiftkey** [comment]
Just remember @dahlbyk: "You are as young as you feel." :grin:

**Pull request merged**
