### PR TITLE
#2209 Show user when there is no matching results

### PR DESCRIPTION
**Pull request by Aliecake**
Lets users know when there are no search results.

Screenshot 2020-10-03 153652

### CODE REVIEW

**Comment by ritwik12** [comment]
@Aliecake Looks good, Thanks for sending this.

@shiftkey Any recommendations for the content of no results matching for current `No projects found with that description...`? Also, about the UI of this.

https://deploy-preview-2378--up-for-grabs-test-bench.netlify.app/#/filters?labels=7&tags=2d-game

**Comment by ritwik12** [comment]
How about something like:
style="color: #2e7ba9; text-indent: 30px; text-transform: uppercase; font-size:25px;"

Feel free to keep and remove anything out of this. Also, do we want `...` or without it?
Screenshot 2020-10-03 at 6 37 12 PM

**Comment by Aliecake** [comment]
@ritwik12 on it

**Comment by ritwik12** [comment]
@Aliecake Please wait for @shiftkey  to give his suggestions also.

**Comment by ritwik12** [comment]
@Aliecake Do you have any other suggestions also for the Front end of that other than what I suggested? I guess @shiftkey is taken up these days with other imp stuffs.

**Comment by ritwik12** [comment]
> How about something like:
> style="color: #2e7ba9; text-indent: 30px; text-transform: uppercase; font-size:25px;"
> 
> Feel free to keep and remove anything out of this. Also, do we want `...` or without it?
> Screenshot 2020-10-03 at 6 37 12 PM

What do you say about this one? Any changes that can make it better? or any other color, size, style you have in mind? @Aliecake

**Comment by Aliecake** [comment]
@ritwik12 I think your suggestions are great, I do think adding a little extra top padding might help readability.

**Comment by ritwik12** [comment]
@Aliecake That would be great, Let's go with that. Please update with extra padding.

**Comment by Aliecake** [comment]
Sorry for the delay with this @ritwik12 . It was a busy week.

**Comment by ritwik12** [comment]
> Sorry for the delay with this @ritwik12 . It was a busy week.

@Aliecake That's fine :)

**Comment by ritwik12** [comment]
@Aliecake Thanks a lott!!!

**Comment by ritwik12** [comment]
Screenshot 2020-10-11 at 12 10 51 PM


@Aliecake Things broke after this PR and had to revert it in #2402. Please check what we did wrong, Netflfy did not showed up in the PR so it got missed and I guess it is breaking the code somewhere.

**Comment by ritwik12** [comment]
@Aliecake Ping, Informing you again in case you missed this. I had to revert your change and you might need to send PR again.

**Pull request merged**
