### PR TITLE
Added supermarket management

### PR DESCRIPTION
**Pull request by jayskhatri**

### CODE REVIEW

**Review by shiftkey — CHANGES_REQUESTED** [review]
@jayskhatri please rename the file to `.yml` as that's what Jekyll requires

**Comment by jayskhatri** [comment]
@shiftkey I have changed the file extension. :)

**Comment by shiftkey** [comment]
@jayskhatri if you could lower-case both of these tags to be consistent with everyone else, everything else is :gem:

```
1 errors found processing projects:
 - _data/projects/Super-Market-Management.yml:
    - Tag 'C' contains invalid characters. Allowed characters: a-z, 0-9, +, #, . or -
    - Tag 'C++' contains invalid characters. Allowed characters: a-z, 0-9, +, #, . or -
```

**Comment by jayskhatri** [comment]
Done @shiftkey

**Review by shiftkey — APPROVED** [review]
Thanks @jayskhatri!

**Pull request merged**
